import Breathing from './lib/loader/BreathingLoader';
import Bubbles from './lib/loader/BubblesLoader';
import Circles from './lib/loader/CirclesLoader';
import CirclesRotationScale from './lib/loader/CirclesRotationScaleLoader';
import ColorDots from './lib/loader/ColorDotsLoader';
import Dots from './lib/loader/DotsLoader';
import DoubleCircle from './lib/loader/DoubleCircleLoader';
import EatBean from './lib/loader/EatBeanLoader';
import Lines from './lib/loader/LinesLoader';
import LineDots from './lib/loader/LineDotsLoader';
import Music from './lib/loader/MusicLoader';
import NineCubes from './lib/loader/NineCubesLoader';
import OpacityDots from './lib/loader/OpacityDotsLoader';
import Pulse from './lib/loader/PulseLoader';
import Ripple from './lib/loader/RippleLoader';
import RotationCircle from './lib/loader/RotationCircleLoader';
import RotationHole from './lib/loader/RotationHoleLoader';
import Text from './lib/loader/TextLoader';

export const BreathingLoader = Breathing;
export const BubblesLoader = Bubbles;
export const CirclesLoader = Circles;
export const CirclesRotationScaleLoader = CirclesRotationScale;
export const ColorDotsLoader = ColorDots;
export const DotsLoader = Dots;
export const DoubleCircleLoader = DoubleCircle;
export const EatBeanLoader = EatBean;
export const LinesLoader = Lines;
export const LineDotsLoader = LineDots;
export const MusicBarLoader = Music;
export const NineCubesLoader = NineCubes;
export const OpacityDotsLoader = OpacityDots;
export const PulseLoader = Pulse;
export const RippleLoader = Ripple;
export const RotationCircleLoader = RotationCircle;
export const RotationHoleLoader = RotationHole;
export const TextLoader = Text;
